### PR TITLE
More refactoring / documentation

### PR DESCRIPTION
**Pull request by johnnyshields**
- Bumped version to 1.1.1
- Refactored "taggable" method into cleaner sub methods
- Added method documentation
- Merged "GroupBy" code into main class
- Added CodeClimate badge
- CodeClimate GPA now at 4.0

As part of the GroupBy merge, this syntax now throws and error:

``` ruby
   class Invalid
      include Mongoid::Document
      include Mongoid::TaggableWithContext::GroupBy::TaggableWithContext  #ERROR!
   end
```

``` ruby
   class Invalid
      include Mongoid::Document
      include Mongoid::TaggableWithContext::GroupBy::AggregationStrategy::RealTime  #ERROR!
   end
```

Instead you need to do this:

``` ruby
   class Valid
      include Mongoid::Document
      include Mongoid::TaggableWithContext
      include Mongoid::TaggableWithContext::AggregationStrategy::RealTimeGroupBy
   end
```

### CODE REVIEW

**Comment by johnnyshields** [comment]
Ready to pull

**Comment by lgs** [comment]
I got a Gem::InvalidSpecificationException :

<pre>
lsoave@ubuntu:~/rails/github/mongoid_taggable_with_context$ gem build mongoid_taggable_with_context.gemspec
ERROR:  While executing gem ... (Gem::InvalidSpecificationException)
    ["lib/mongoid/taggable_with_context/group_by/aggregation_strategy/real_time.rb", "lib/mongoid/taggable_with_context/group_by/taggable_with_context.rb"] are not files
</pre>

... fixed & bumped 1.1.1 version ( commit 83d34eb93364593a9a619bc37bf87f66ccfc65ed and 7af6342f3cf579bbbbfdf00c7dd1914d0dfba0a4 )

56 spec examples, 0 failures  ... but,     Rvm: 1.9.3 / Rvm: 2.0.0 fail to build on  Travis CI ( still not understand way ... )

**Comment by lgs** [comment]
... ok I found:

 Travis CI build the commit with the command `bundle install --without development`, than it was missing all development gems, as well as rake gem. 

Changing `group :development` in `group :test` with rake added, solve the issue ....

Now we are green on both Rvm: 1.9.3 and Rvm: 2.0.0 ( see https://travis-ci.org/lgs/mongoid_taggable_with_context/builds/7307105 )

**Comment by johnnyshields** [comment]
Thanks for for fixing didn't realize I had broken the Travis (d'oh.)

**Pull request merged**
